project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Tidyverse"
            file: 01_tidyverse.qmd
          - text: "02 Data Acquisition"
            file: 02_data_acquisition.qmd
          - text: "03 Data Wrangling"
            file: 03_data_wrangling.qmd
          - text: "04 Data Visualization"
            file: 04_data_visualization.qmd


format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto